### ISSUE TITLE
External Spawn Trigger?

### ISSUE THREAD

**Issue by MasterAirscrachDev** [Twingamerdudes/Montyverse#1]
## Love the mods, Ive speedrun both Montyverse and Multiverse.
I was wondering wether you would be able to make a version that instead of spawning every 15 seconds, it spawned them when an external criteria was met. (eg, check if theres a file and spawn)
That way you could make (for example) a live chat integration that can create a file to request a spawn.
I'm not great in unreal blueprints but i could easily make a twitch integration for it

**Comment by Twingamerdudes** [comment]
Well, what you can do is make a twitch bot that presses keys when a user types !spawnmonty. Then in the blueprint, it detects that key press and makes the monty spawn. I can implement it for you if you want! Hope this helps! Contact me on the FNAF Security breach server here: https://discord.gg/2SmcuhC6uf
